runtime: nodejs20
# Environment variables can be set here, but for sensitive data (like DB passwords),
# it is better to set them via the command line or the Google Cloud Console.
# env_variables:
#   MONGO_URI: "your-connection-string"
